version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: 'mosquitto'
    volumes:
      - ./mosquitto:/mosquitto/config
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - default

  worker:
    build: ./worker
    depends_on:
      - mosquitto
    environment:
      WAIT_HOSTS: mosquitto:1883
    networks:
      - default

networks:
  default:
    driver: bridge
